------------------------------------------------------------  2018-06-20  Version 5.0  Compatible with CONREC version 4.0 ------------------------------------------------------------ Major refactor. Total refactor. - Search for the contact in a file list. - Read file list from the CONTACTSPATH environment variable - Remove the file_name command line option - Check for and correct a conrec ver 3.0 record - Display the Role information in the output - Almost a total rewrite

diff --git a/contact b/contact
--- a/contact
+++ b/contact
@@ -1,56 +1,162 @@
 #! /bin/bash
 
+# Uses environment variable CONTACTSPATH
+
 # ----------------------------------------
 # Constants
 # ----------------------------------------
 readonly origIFS=$IFS
-readonly progVer="4.1"
+readonly progVer="5.0"
 readonly progName=$(basename $0)
 readonly uninitialized="UNINITIALIZED"
 readonly allRecords="FALSE"
-readonly defaultSearchFileName="${HOME}/cloud_storage/Dropbox (cPrime Inc.)/for David Bacon/cPrime.txt"
-
-# ----------------------------------------
-# ToDo
-# ----------------------------------------
-# - Search multiple files in a list,using the $PATH syntax
-# - Add these to the search list
-#   /Users/thedrub/cloud_storage/Dropbox\ \(Personal\)/doc/journal.txt
-#   /Users/thedrub/Sync/Work/Agile/agile.txt"
+#readonly fileSearchList="\
+#${HOME}/cloud_storage/Dropbox (cPrime Inc.)/for David Bacon/cPrime.txt\
+#:${HOME}/Sync/Work/Agile/agile.txt\
+#"
 
 # ----------------------------------------
 # Globals
 # ----------------------------------------
-debug="TRUE"    #debug
-debug="FALSE"   #debug
+debug="TRUE"
+debug="FALSE"
 recordCount=0
 
 
+# ----------------------------------------
+# Libraries
+# ----------------------------------------
+libList="${HOME}/bin/lib/dashline"
+
+for i in $libList; do
+    if [[ -r $i ]]; then    # Does it exist?
+        . $i                # Source the library file.
+    else
+        printf "%s\n" "ERROR: Library file not found. Could not source library file."
+        printf "%s\n" "File: $i"
+        exit
+    fi
+done
+
+
+# ----------------------------------------
+# Startup
+# ----------------------------------------
 if [ "$debug" == "TRUE" ]; then
-  echo "++ 0 ........................ .$0."   #debug
-  echo "++ 1 ........................ .$1."   #debug
-  echo "++ 2 ........................ .$2."   #debug
-  echo "++ \$* ...................... .$*."    #debug
-  echo "++ progName ................. .$progName."    #debug
-  echo "++ Default fname ............ .$defaultSearchFileName."
+    printf "%s\n" "
+** ==================== Startup
+** 0 ........................ .$0.
+** 1 ........................ .$1.
+** \$* ....................... .$*.
+** progName ................. .$progName.
+** File search list ......... .$fileSearchList."
 fi
+
+
+# ----------------------------------------
+  function Initialize () {
+# ----------------------------------------
+    # Check to assure the search path environment variable is set.
+    # If not set, then exit
+    if [[  -z ${CONTACTSPATH:-} ]]; then
+        printf "%s\n" "\
+ERROR: Environment variable not set. 
+       The CONTACTSPATH variable must contain a list of files.
+"
+       exit 1
+    fi
+}   #function
+
 
 # ----------------------------------------
   function ProgUsage () {
 # ----------------------------------------
-  echo "Syntax:"
-  echo "  $progName search_name [ file_name  ]"
-  echo "  contact -h"
-  echo
-  echo "Where"
-  echo "  search_name is a string used for the search"
-  echo "  file_name is a file to search."
-  echo
-  echo "Defaults"
-  echo "  file_name: $defaultSearchFileName"
-  echo
-  echo "Version: $progVer"
+  printf "%s\n"  "
+Syntax:
+$progName search_name [ file_name  ]
+  contact -h
+
+Where
+  search_name is a string used for the search
+  file_name is a file to search.
+
+Defaults
+  A file list is stored in a variable in the script.
+
+Version: $progVer"
+
 }	# function
+
+
+# ----------------------------------------
+  function SearchFile () {
+# ----------------------------------------
+# Parameters
+local fileName=$1
+local stringToFind=$2
+
+local fileBaseName=$(basename $fileName)
+
+    if [[ "$debug" == "TRUE" ]]; then
+        printf "%s\n" "\
+**** ==================== function: $FUNCNAME
+  ** fileName ............ .${fileName}.
+  ** fileBaseName ........ .${fileBaseName}.
+  ** stringToFind ........ .${stringToFind}."
+    fi
+
+grep "CONREC::" ${fileName} | grep -i ${stringToFind} | \
+    while read recordType junk recordVer junk recordDate junk firstStr junk lastStr junk emailStr junk phoneStr junk orgStr junk roleStr junk remainingStr
+    do
+        recordCount=$((recordCount+1))  # Increment recordCount
+
+        # There is a field order change between conrec ver 3.0 and 4.0
+        # The recordVer and recordDate order was reveresed.
+        # If recordDate = "3.0", then it is a conrec ver 3.0 format, so let's
+        # swith the values in those 2 fields.
+        if [ "$recordDate" == "3.0" ]; then
+            recordDate=${recordVer}
+            recordVer="3.0"
+        fi
+
+        if [ "$debug" == "TRUE" ]; then
+            printf "%s\n" "\
+  ** recordcount ......... $recordCount
+  ** recordType .......... $recordType
+  ** recordVer ........... $recordVer
+  ** recordDate .......... $recordDate
+  ** firstStr ............ $firstStr
+  ** lastStr ............. $lastStr
+  ** emailStr ............ $emailStr
+  ** phontStr ............ $phoneStr
+  ** orgStr .............. $orgStr
+  ** roleStr ............. $roleStr
+  ** remainingStr ........ $remainingStr"
+        fi
+
+        if [[ $recordCount == 1 ]]; then
+
+            printf "%s\n" "=========== $progName  v$progVer ========== File: $fileBaseName =========="
+        fi
+
+        printf "%s\n" "\
+  Name ............ $firstStr $lastStr
+  Phone ........... $phoneStr
+  email ........... $emailStr"
+
+        if [[ ! -z $remainingStr ]]; then
+            printf "%s\n" "    Note .......... $remainingStr"
+        fi
+
+        printf "%s\n" "\
+    Role, Org ..... $roleStr, $orgStr
+    Created ....... $recordDate                Record Ver: $recordVer"
+
+        DashLine 65 "-"
+
+    done
+}   # function
+
 
 # ----------------------------------------
 # ----------------------------------------
@@ -58,80 +164,45 @@ fi
 # ----------------------------------------
 # ----------------------------------------
 
-if [[ -z $1 ]]; then
-  echo
-  echo "ERROR: search_name not supplied."
-  echo "ERROR: file_name not supplied."
-  echo
-  ProgUsage
-  printf "\n"
-  exit
-else
-  searchStr=$1 
+Initialize
+readonly fileSearchList=$CONTACTSPATH
 
-  # See if a Usage message was requested, the "-h" flag
-  if [[ "${searchStr}" = "-h" ]]; then
+if [[ -z $1 ]]; then
+    printf "%s\n
+ERROR: search_name not supplied.
+"
     ProgUsage
     exit
-  fi
-fi
-
-if [[ -z $2 ]]; then
-  # if param #2 is unset ...
-  # Assume the cPrime.txt file should be used.
-  searchFileName=$defaultSearchFileName
 else
-  searchFileName=$2
+    searchStr=$1 
+
+    # See if a Usage message was requested, the "-h" flag
+    if [[ "${searchStr}" = "-h" ]]; then
+        ProgUsage
+        exit
+    fi
 fi
 
-# Error if the file name does not exist
-if [[ ! -f $searchFileName ]]; then
-  echo "ERROR: File does not exist."
-  echo "  search_name: $searchFileName"
-fi
 
-# Parse CONREC version 3.0 record format
-IFS=":"
-grep "CONREC::"  $searchFileName | grep -i $searchStr | \
-while read recordType junk recordVer junk recordDate junk firstStr junk lastStr junk emailStr junk phoneStr junk orgStr junk roleStr junk remainingStr 
+IFS=:
+for searchFileName in $fileSearchList; do
 
-  do
-    recordCount=$((recordCount+1))  # Increment recordCount
-
-    if [ "$debug" == "TRUE" ]; then
-      echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-      echo "++ recordType ......... .$recordType."
-      echo "++ recordVer .......... .$recordVer."
-      echo "++ Date ............... .$recordDate."
-      echo "++ recordVer .......... .$recordVer."
-      echo "++ firstStr ........... .$firstStr."
-      echo "++ lastStr ............ .$lastStr."
-      echo "++ emailStr ........... .$emailStr."
-      echo "++ phoneStr ........... .$phoneStr."
-      echo "++ orgStr ............. .$orgStr."
-      echo "++ roleStr ............ .$roleStr."
-      echo "++ remainingStr ....... .$remainingStr.".
-      #printf "++ %-.20s %s\n" "orgStr .................................." "$orgStr"
+    if [ -f $searchFileName ]; then
+        if [ "$debug" == "TRUE" ]; then
+            printf "%s\n" "\
+** ==================== Main: $progName
+** searchFileName .................... $searchFileName
+** searchStr ......................... $searchStr "
+       fi
+        SearchFile "$searchFileName" "$searchStr"
+    else
+        printf "%s\n" "
+ERROR: A file listed in the environment variable CONTACTSPATH does not exist.
+       File: $searchFileName
+"
     fi
-
-    if [[ $recordCount == 1 ]]; then
-
-      printf " ---------------------------------------- $progName  v$progVer -----\n"
-    fi
-    echo "   Name ........ $firstStr $lastStr"
-    echo "   Phone ....... $phoneStr"
-    echo "   email ....... $emailStr"
-
-      if [[ ! -z $remainingStr ]]; then
-        echo "     Note ...... $remainingStr"
-      fi
-
-    echo "     Org ....... $orgStr"
-    echo "     Created ... $recordDate                Record Ver: $recordVer"
-
-    printf " ------------------------------------------------------------"
-    printf "\n"
-  done
+done
+unset IFS
 
 
 
@@ -141,11 +212,28 @@ while read recordType junk recordVer junk recordDate junk firstStr junk lastStr 
 # ----------------------------------------
 # ----------------------------------------
 
-# ----------------------------------------------------------------------
-# 2018-06-07
-# Version 4.1
-# Compatible with CONREC version 4.0
-# ----------------------------------------------------------------------
+----------------------------------------
+  History
+----------------------------------------
+
+------------------------------------------------------------
+ 2018-06-20
+ Version 5.0
+ Compatible with CONREC version 4.0
+------------------------------------------------------------
+Major refactor. Total refactor.
+- Search for the contact in a file list.
+- Read file list from the CONTACTSPATH environment variable
+- Remove the file_name command line option
+- Check for and correct a conrec ver 3.0 record
+- Display the Role information in the output
+- Almost a total rewrite
+
+------------------------------------------------------------
+ 2018-06-07
+ Version 4.1
+ Compatible with CONREC version 4.0
+------------------------------------------------------------
 Changed progVersion to 4.1
 
 The records were not being displayed properly.
@@ -172,12 +260,11 @@ Added the progName variable.
 - Added to debug output
 - Added to user output
 
-
-# ----------------------------------------------------------------------
-# 2018-04-20
-# Version 4.0
-# Compatible with CONREC version 4.0
-# ----------------------------------------------------------------------
+----------------------------------------------------------------------
+ 2018-04-20
+ Version 4.0
+ Compatible with CONREC version 4.0
+----------------------------------------------------------------------
 Note: There was no version 3.0 of this script. Trying to keep the record
 script and this script versions in sync. Maybe it's useful?
 
@@ -193,11 +280,11 @@ Ver 4.0 CONREC record changed. Moved ver. Added a role.
      Created ... 2018-06-07                Record Ver: 4.0
  ------------------------------------------------------------
 
-# ----------------------------------------------------------------------
-# 2018-04-19
-# Version 2.0
-# Compatible with CONREC version 3.0
-# ----------------------------------------------------------------------
+----------------------------------------------------------------------
+ 2018-04-19
+ Version 2.0
+ Compatible with CONREC version 3.0
+----------------------------------------------------------------------
 - If the file name is not supplied, use a default search file.
     Default = cPrime.txt in the cPrime directory
 - Much more error checking on input parameters
@@ -217,11 +304,11 @@ Ver 4.0 CONREC record changed. Moved ver. Added a role.
  ------------------------------------------------------------
 
 
-# ----------------------------------------------------------------------
-# 2018-04-17
-# Version 1.0
-# Compatible with CONREC version 3.0
-# ----------------------------------------------------------------------
+----------------------------------------------------------------------
+ 2018-04-17
+ Version 1.0
+ Compatible with CONREC version 3.0
+----------------------------------------------------------------------
 "contact dane < cPrime.txt" produces this output:
 
  -------------------------------------------------- 1.0 -----
